package evo_sim.view.swing.monadic

import cats.effect.IO
import javax.swing.event.ChangeListener
import javax.swing.JSlider

/** A class that provides a monadic description of the operations supplied by Swing's [[JSlider]] in the form
 * of IO monad in a purely functional fashion.
 * @param component the jSlider that this class wraps.
 */
class JSliderIO(override val component: JSlider) extends JComponentIO(component){

  /** Returns an [[IO]] containing the description of a [[JSlider#setMinimum]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def minimumSet(min: Int): IO[Unit] = IO { component.setMinimum(min) }

  /** Returns an [[IO]] containing the description of a [[JSlider#setMaximum]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def maximumSet(max: Int): IO[Unit] = IO { component.setMaximum(max) }

  /** Returns an [[IO]] containing the description of a [[JSlider#setValue]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def valueSet(value: Int): IO[Unit] = IO { component.setValue(value) }

  /** Returns an [[IO]] containing the description of a [[JSlider#getValue]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def valueGot: IO[Int] = IO { component.getValue }

  /** Returns an [[IO]] containing the description of a [[JSlider#setMajorTickSpacing]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def majorTickSpacingSet(spacing: Int): IO[Unit] = IO { component.setMajorTickSpacing(spacing) }

  /** Returns an [[IO]] containing the description of a [[JSlider#setMinorTickSpacing]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def minorTickSpacingSet(spacing: Int): IO[Unit] = IO { component.setMinorTickSpacing(spacing) }

  /** Returns an [[IO]] containing the description of a [[JSlider#setPaintTicks]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def paintTicksSet(b: Boolean): IO[Unit] = IO { component.setPaintTicks(b) }

  /** Returns an [[IO]] containing the description of a [[JSlider#setPaintLabels]]
   * method invocation on the [[JSlider]] wrapped in this instance. */
  def paintLabelsSet(b: Boolean): IO[Unit] = IO { component.setPaintLabels(b) }

  //procedural event listener description:
  /** Returns an [[IO]] that registers an [[ChangeListener]] for handling the
   * [[javax.swing.event.ChangeEvent]]s generated by the JSliderIO wrapped by this instance.
   * It accepts as parameter a procedural specification of the listener instead of a
   * monadic one.
   * @see [[MonadicChangeListener]] and [[monadicChangeListenerAdded]] for a monadic
   *      listener description.*/
  def changeListenerAdded(l: ChangeListener): IO[Unit] = IO {component.addChangeListener(l)}

  /** Returns an [[IO]] containing the code for unregistering the given [[ChangeListener]] from
   * the JSliderIO wrapped by this instance. */
  def changeListenerRemoved(l: ChangeListener): IO[Unit] = IO {component.removeChangeListener(l)}

  //monadic event listener description:
  /** Returns an [[IO]] that registers a [[MonadicChangeListener]] for handling the
   * [[javax.swing.event.ChangeEvent]]s generated by the JSliderIO wrapped by this instance.
   * It accepts as parameter a monadic specification of the listener instead of a
   * procedural one.
   *
   * @see [[changeListenerAdded]] for a procedural listener description.*/
  def monadicChangeListenerAdded(l: MonadicChangeListener): IO[Unit] =
    IO { component.addChangeListener(l(_).unsafeRunSync())}

  /** Returns an [[IO]] containing the code for unregistering the given [[MonadicChangeListener]] from
   * the [[JSlider]] wrapped by this instance. */
  def monadicChangeListenerRemoved(l: MonadicChangeListener): IO[Unit] =
    IO {component.removeChangeListener(l(_).unsafeRunSync())}

}


/** A factory for [[IO]]s containing a JSliderIO instance.*/
object JSliderIO{
  def apply(): IO[JSliderIO] = IO { new JSliderIO(new JSlider) }
}