package evo_sim.model

object Constants {

  val WORLD_WIDTH = 1280
  val WORLD_HEIGHT = 720

  val ITERATIONS_PER_DAY = 500

  val TEMPERATURE_AMPLITUDE = 1.0125f
  val LUMINOSITY_AMPLITUDE = 1.05f
  val FOW_AMPLITUDE = 2f
  val VELOCITY_AMPLITUDE = 2f

  val DEF_BLOB_RADIUS = 5
  val DEF_BLOB_LIFE = 999999
  val DEF_BLOB_VELOCITY = 50
  val DEF_BLOB_SLOW_VELOCITY: Int = DEF_BLOB_VELOCITY / 2
  val DEF_BLOB_FOW_RADIUS = 50
  val DEF_BLOB_DEAD = 0

  val DEF_FOOD_HEIGHT = 10
  val DEF_REPRODUCING_FOOD_HEIGHT = 15
  val DEF_POISONOUS_FOOD_HEIGHT = 12
  val DEF_FOOD_LIFE = 500

  val DEF_PUDDLE_WIDTH = 50
  val DEF_PUDDLE_HEIGHT = 35

  val DEF_STONE_WIDTH = 15
  val DEF_STONE_HEIGHT = 12

  val DEF_STANDARD_PLANT_WIDTH = 7
  val DEF_STANDARD_PLANT_HEIGHT = 10
  val DEF_REPRODUCING_PLANT_WIDTH = 10
  val DEF_REPRODUCING_PLANT_HEIGHT = 10
  val DEF_POISONOUS_PLANT_WIDTH = 8
  val DEF_POISONOUS_PLANT_HEIGHT = 10

  val DEF_COOLDOWN = 50
  val DEF_DAMAGE = 25
  val DEF_MOD_PROP_RANGE = 5
  val DEF_FOOD_ENERGY = 10

  val MIN_BLOBS = 0
  val MAX_BLOBS = 300
  val DEF_BLOBS = 50

  val MIN_PLANTS = 0
  val MAX_PLANTS = 300
  val DEF_PLANTS = 50

  val MIN_OBSTACLES = 0
  val MAX_OBSTACLES = 100
  val DEF_OBSTACLES = 20

  val DEF_LIFECYCLE = 200

  val MIN_LUMINOSITY = 0
  val MAX_LUMINOSITY = 200
  val DEFAULT_LUMINOSITY = 100

  val MIN_TEMPERATURE: Int = -20
  val MAX_TEMPERATURE = 75
  val DEF_TEMPERATURE = 25

  val MIN_DAYS = 0
  val MAX_DAYS = 365
  val DEF_DAYS = 30

  val TEMPERATURE_MAX_DELTA = 25 // ricavabile?
  val LUMINOSITY_MAX_DELTA = 50 // ricavabile?

  val SELECTABLE_MAX_LUMINOSITY: Int = MAX_LUMINOSITY - LUMINOSITY_MAX_DELTA
  val SELECTABLE_MIN_LUMINOSITY: Int = MIN_LUMINOSITY

  val SELECTABLE_MAX_TEMPERATURE: Int = MAX_TEMPERATURE - TEMPERATURE_MAX_DELTA
  val SELECTABLE_MIN_TEMPERATURE: Int = MIN_TEMPERATURE

  val NEXT_DIRECTION = 0

  val VELOCITY_SLOW_DECREMENT = 10

  val SLOWBLOB_TYPE = "SlowBlob"
  val POISONBLOB_TYPE = "PoisonBlob"

}
